version: "3"
services:
    ticker-db:
        container_name: 'ticker-db'
        image: mariadb:10.2
        env_file: /etc/env/ticker.env
        networks:
            - tickernetwork 
        ports:
            - 33306:3306
        # restart: on-failure
        volumes:
            - ./testdb4:/var/lib/mysql
            # - ./dbconfig/my.cnf:/etc/mysql/my.cnf
    
    dashboard:
        build: .
        hostname: ticker-dashboard
        command: /startservices
        env_file: /etc/env/ticker.env
        ports:
            - 8042:5015
            - 8043:80
        volumes:
            - ./:/app/
            - /opt/docker/ticker/logs:/app/logs
        depends_on:
            - db
        networks:
            - tickernetwork
    
networks:
  tickernetwork:
    external: true