version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  dct-django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: dct-local_django
    restart: always
    network_mode: bridge
    links:
      - postgres
      - redis
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/venv/
      - ./tmp:/tmp
      #- /usr/local/lib/python3.7

    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "1001:8000"
      - "19001:5678"
    command: /start

  # venv:
  #   build:
  #     context: .
  #     dockerfile: ./compose/local/django/Dockerfile
  #   image: venv
  #   volumes:
  #     - .:/app
  #   env_file:
  #     - ./.envs/.local/.django
  #     - ./.envs/.local/.postgres
  #   command: 'ping gmail.com'

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: dct-production_postgres
    network_mode: bridge
    volumes:
      - ./db_all/${DB_NAME}:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    restart: always
    ports:
      - "5431:5432"
#redis-server --requirepass yourpassword
  redis:
    image: redis:6.0.9-alpine
    restart: always
    network_mode: bridge


  celeryworker:
    <<: *django
    image: local_celeryworker
    container_name: dct-celeryworker
    network_mode: bridge
    restart: always
    depends_on:
      - redis
      - postgres

    volumes:
      - .:/app
      - ./tmp:/tmp
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: local_celerybeat
    container_name: dct-celerybeat
    network_mode: bridge
    restart: always
    depends_on:
      - redis
      - postgres

    ports: []
    command: /start-celerybeat
    network_mode: bridge
    volumes:
      - .:/app
      - ./tmp:/tmp


  flower:
    <<: *django
    image: local_flower
    container_name: dct-flower
    network_mode: bridge
    restart: always
    ports:
      - "21001:5555"
    command: /start-flower
    volumes:
      - .:/app


