services:
  mariadb:
    image: mariadb:10.7
    ports:
      - 33306:3306
    volumes:
      - ~/apps/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1
      - MYSQL_PASSWORD=1
      - MYSQL_USER=Ticker
      - MYSQL_DATABASE=Ticker

    network_mode: bridge