# Generated by Django 4.0.5 on 2022-07-08 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SetUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FQDN', models.CharField(max_length=60)),
                ('Dvs_Token', models.CharField(max_length=150, null=True)),
                ('Rundeck_Token', models.CharField(max_length=150, null=True)),
                ('Apache_server_url', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tv_condition_before', models.CharField(max_length=200)),
                ('tv_condition_after', models.CharField(max_length=200)),
                ('room_no', models.CharField(max_length=200)),
                ('key', models.CharField(max_length=200)),
                ('ipad_condition_before', models.CharField(max_length=200)),
                ('ipad_condition_after', models.CharField(max_length=200)),
                ('completed', models.BooleanField(blank=True, default=False, null=True)),
                ('ip', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TickerDetails',
            fields=[
                ('ticker_id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker_type', models.CharField(max_length=60)),
                ('ticker_title', models.CharField(default='Not Specific', max_length=50)),
                ('ticker_json', models.TextField(blank=True)),
                ('ticker_start_time', models.DateTimeField(null=True)),
                ('ticker_end_time', models.DateTimeField(null=True)),
                ('wings', models.CharField(max_length=300, null=True)),
                ('floors', models.CharField(max_length=300, null=True)),
                ('rooms', models.CharField(max_length=300, null=True)),
                ('frequency', models.CharField(max_length=30, null=True)),
                ('occuring_days', models.CharField(max_length=50, null=True)),
                ('ticker_priority', models.CharField(default='Not Specific', max_length=10)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_on', models.DateTimeField()),
                ('modified_by', models.CharField(blank=True, max_length=50, null=True)),
                ('modified_on', models.DateTimeField()),
                ('is_active', models.PositiveIntegerField()),
                ('is_deleted', models.PositiveIntegerField()),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TickerHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker_id', models.PositiveIntegerField()),
                ('ticker_type', models.CharField(max_length=40)),
                ('ticker_title', models.CharField(default='Not Specific', max_length=50)),
                ('ticker_json', models.TextField(blank=True)),
                ('ticker_start_time', models.DateTimeField(null=True)),
                ('ticker_end_time', models.DateTimeField(null=True)),
                ('wings', models.CharField(max_length=300, null=True)),
                ('floors', models.CharField(max_length=300, null=True)),
                ('rooms', models.CharField(max_length=300, null=True)),
                ('frequency', models.CharField(max_length=30, null=True)),
                ('occuring_days', models.CharField(max_length=50, null=True)),
                ('ticker_priority', models.CharField(default='Not Specific', max_length=10)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_on', models.DateTimeField()),
                ('modified_by', models.CharField(blank=True, max_length=50, null=True)),
                ('modified_on', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.PositiveIntegerField()),
                ('is_deleted', models.PositiveIntegerField()),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish')),
                ('body', models.TextField()),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
