# Generated by Django 4.0.5 on 2022-07-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RundeckLog',
            fields=[
                ('rundeck_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ticker_id', models.IntegerField(null=True)),
                ('ticker_title', models.CharField(max_length=150, null=True)),
                ('execution', models.CharField(default='Pending', max_length=150, null=True)),
                ('successfull_nodes', models.TextField(blank=True, default='None', null=True)),
                ('failed_nodes', models.TextField(blank=True, default='None', null=True)),
                ('tv_status', models.CharField(default='None', max_length=150, null=True)),
                ('iPad_status', models.CharField(default='None', max_length=150, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='tickerdetails',
            name='rundeckid',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tickerhistory',
            name='rundeckid',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
