# Generated by Django 4.0.5 on 2022-07-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='Ticker_FQDN',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
