# Generated by Django 4.0.5 on 2022-07-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker_management', '0002_rundecklog_tickerdetails_rundeckid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='Rundeck_start_Job',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='setup',
            name='Rundeck_stop_Job',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
