# Generated by Django 4.0.4 on 2022-07-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker_management', '0002_tickerdetails_ticker_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tv_condition_before', models.CharField(max_length=200)),
                ('tv_condition_after', models.CharField(max_length=200)),
                ('room_no', models.CharField(max_length=200)),
                ('key', models.CharField(max_length=200)),
                ('ip', models.CharField(max_length=200)),
                ('ipad_condition_before', models.CharField(max_length=200)),
                ('ipad_condition_after', models.CharField(max_length=200)),
                ('completed', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
