# Generated by Django 4.0.5 on 2022-07-20 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticker_management', '0003_setup_rundeck_start_job_setup_rundeck_stop_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setup',
            old_name='Rundeck_start_Job',
            new_name='Rundeck_Start_Job',
        ),
        migrations.RenameField(
            model_name='setup',
            old_name='Rundeck_stop_Job',
            new_name='Rundeck_Stop_Job',
        ),
    ]
