# Generated by Django 4.0.5 on 2022-07-04 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker_management', '0003_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickerdetails',
            name='ticker_msg',
            field=models.CharField(default='Not Specific', max_length=50),
        ),
    ]
