# Generated by Django 4.0.5 on 2022-07-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker_management', '0004_rename_rundeck_start_job_setup_rundeck_start_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickerhistory',
            name='roomTypeSelection',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tickerhistory',
            name='modified_on',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tickerhistory',
            name='occuring_days',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tickerhistory',
            name='ticker_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tickerhistory',
            name='ticker_type',
            field=models.CharField(max_length=60),
        ),
    ]
