# Generated by Django 4.0.5 on 2022-07-04 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker_management', '0004_tickerdetails_ticker_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickerhistory',
            name='ticker_msg',
            field=models.CharField(default='Not Specific', max_length=50),
        ),
    ]
