# Generated by Django 4.0.5 on 2022-07-04 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticker_management', '0005_tickerhistory_ticker_msg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickerdetails',
            old_name='ticker_msg',
            new_name='ticker_title',
        ),
        migrations.RenameField(
            model_name='tickerhistory',
            old_name='ticker_msg',
            new_name='ticker_title',
        ),
    ]
