# Generated by Django 4.0.5 on 2022-07-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker_management', '0006_rename_ticker_msg_tickerdetails_ticker_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickerdetails',
            old_name='created_for',
            new_name='wings',
        ),
        migrations.RemoveField(
            model_name='tickerhistory',
            name='created_for',
        ),
        migrations.AddField(
            model_name='tickerdetails',
            name='floors',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='tickerdetails',
            name='rooms',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='tickerdetails',
            name='ticker_priority',
            field=models.CharField(default='Not Set', max_length=10),
        ),
        migrations.AddField(
            model_name='tickerhistory',
            name='floors',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='tickerhistory',
            name='rooms',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='tickerhistory',
            name='ticker_priority',
            field=models.CharField(default='Not Set', max_length=10),
        ),
        migrations.AddField(
            model_name='tickerhistory',
            name='wings',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
