# Generated by Django 4.0.5 on 2022-07-04 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticker_management', '0007_rename_created_for_tickerdetails_wings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickerdetails',
            name='reason_for_delete',
        ),
        migrations.RemoveField(
            model_name='tickerhistory',
            name='reason_for_delete',
        ),
    ]
