# Generated by Django 2.2.7 on 2020-02-20 11:33

from django.db import migrations, models
import django.db.models.deletion
import ipad_config.models


class Migration(migrations.Migration):

    dependencies = [
        ('ipad_config', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='javaconfig',
            options={'permissions': [('can_bulk_unsync', 'Can change the status of javaconfig to unsync')]},
        ),
        migrations.AlterModelOptions(
            name='settingsimages',
            options={'permissions': [('bulk_delete_settingassets', 'Can delete all settings assets')]},
        ),
        migrations.AlterModelOptions(
            name='uploadqueue',
            options={'ordering': ('-created_on',)},
        ),
        migrations.RenameField(
            model_name='uploadqueue',
            old_name='message',
            new_name='error',
        ),
        migrations.RemoveField(
            model_name='hotelservices',
            name='ipadbasemodel_ptr',
        ),
        migrations.RemoveField(
            model_name='splashimages',
            name='ipadbasemodel_ptr',
        ),
        migrations.RemoveField(
            model_name='splashimages',
            name='room_type',
        ),
        migrations.AddField(
            model_name='exportqueue',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelservices',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='splashimages',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='splash_images', to='ipad_config.Hotel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='splashimages',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dvlanguagecode',
            name='lang_id',
            field=models.AutoField(db_column='lang_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='exportqueue',
            name='created_by',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='exportqueue',
            name='modified_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hotelservices',
            name='is_active',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], default=1),
        ),
        migrations.AlterField(
            model_name='javaconfig',
            name='val_type',
            field=models.CharField(choices=[('common', 'common'), ('environment', 'environment'), ('environment_substring', 'environment_substring')], default='text', max_length=50),
        ),
        migrations.AlterField(
            model_name='mainfeatures',
            name='app_version',
            field=models.CharField(blank=True, default=1, max_length=255),
        ),
        migrations.AlterField(
            model_name='mainfeatures',
            name='controller_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='mainfeatures',
            name='room_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='uploadqueue',
            name='upload_type',
            field=models.CharField(choices=[('THEME', 'THEME'), ('ASSET_ZIP', 'ASSET_ZIP'), ('LANGUAGE', 'LANGUAGE'), ('MAIN_FEATURES', 'MAIN_FEATURES'), ('COMMON_SETTINGS', 'COMMON_SETTINGS'), ('FEATURE_SETTINGS', 'FEATURE_SETTINGS'), ('HOME_FEATURE', 'HOME_FEATURE')], max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='colorstylemapping',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='HotelImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetType', models.CharField(default='image', max_length=255)),
                ('_assetTimestamp', models.DateTimeField(auto_now_add=True)),
                ('assetName', models.FileField(blank=True, null=True, upload_to=ipad_config.models.get_hotel_images_upload_path)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_images', to='ipad_config.Hotel')),
            ],
            options={
                'permissions': [('bulk_delete_hotelimages', 'Can delete all hotel images')],
            },
        ),
        migrations.AddField(
            model_name='hotelservices',
            name='icon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ipad_config.HotelImages'),
        ),
        migrations.AddField(
            model_name='splashimages',
            name='icon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ipad_config.HotelImages'),
        ),
        migrations.CreateModel(
            name='HotelAirportDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('position', models.IntegerField()),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipad_config.AirportDetail')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_airport_details', to='ipad_config.Hotel')),
            ],
            options={
                'unique_together': {('hotel', 'airport')},
            },
        ),
        migrations.CreateModel(
            name='DVHotelLanguageCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, default=0, max_length=255)),
                ('is_active', models.IntegerField(default=1)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_langauge_codes', to='ipad_config.Hotel')),
                ('language_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipad_config.DVLanguageCode')),
            ],
            options={
                'unique_together': {('hotel', 'language_code')},
            },
        ),
        migrations.CreateModel(
            name='DVHotelLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField(blank=True, null=True)),
                ('field', models.TextField(blank=True, null=True)),
                ('lang_code', models.CharField(blank=True, max_length=255, null=True)),
                ('module_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='ipad_config.Hotel')),
            ],
            options={
                'unique_together': {('hotel', 'tag', 'lang_code')},
            },
        ),
    ]
