# Generated by Django 2.2.7 on 2020-04-04 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipad_config', '0002_auto_20200220_1133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dvhotellanguage',
            options={'ordering': ('lang_code', 'tag', 'field')},
        ),
        migrations.AlterModelOptions(
            name='dvlanguage',
            options={'ordering': ('lang_code', 'tag', 'field')},
        ),
        migrations.AlterModelOptions(
            name='uploadqueue',
            options={'ordering': ('created_on',)},
        ),
        migrations.AlterField(
            model_name='uploadqueue',
            name='upload_type',
            field=models.CharField(choices=[('THEME', 'THEME'), ('ASSET_ZIP', 'ASSET_ZIP'), ('LANGUAGE', 'LANGUAGE'), ('MAIN_FEATURES', 'MAIN_FEATURES'), ('COMMON_SETTINGS', 'COMMON_SETTINGS'), ('FEATURE_SETTINGS', 'FEATURE_SETTINGS'), ('HOME_FEATURE', 'HOME_FEATURE'), ('AIRPORT_DETAILS', 'AIRPORT_DETAILS'), ('AIRLINE_DETAILS', 'AIRLINE_DETAILS')], max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='dvhotellanguage',
            unique_together={('hotel', 'tag', 'lang_code', 'module_name')},
        ),
        migrations.CreateModel(
            name='DVHomeService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_name', models.CharField(default='', max_length=255)),
                ('selected_image_name', models.CharField(default='', max_length=255)),
                ('type', models.CharField(default='with_image', max_length=255)),
                ('feature', models.CharField(default='with_image', max_length=255)),
                ('size', models.CharField(max_length=255)),
                ('command', models.CharField(default='with_image', max_length=255)),
                ('position', models.IntegerField(default=1)),
                ('enabled', models.IntegerField(choices=[(0, '0'), (1, '1')], default=1)),
                ('is_evening', models.IntegerField(blank=True, null=True)),
                ('is_morning', models.IntegerField(blank=True, null=True)),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_services', to='ipad_config.Hotel')),
            ],
            options={
                'unique_together': {('hotel', 'name')},
            },
        ),
    ]
