# Generated by Django 2.2.7 on 2020-10-16 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipad_config', '0003_auto_20200404_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='JavaConfigChanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_by', models.CharField(max_length=100)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipad_config.Hotel')),
                ('java_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipad_config.JavaConfig')),
            ],
        ),
    ]
