# Generated by Django 2.2.7 on 2020-12-05 04:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipad_config', '0005_auto_20201112_0652'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultFileChanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('deleted', django.contrib.postgres.fields.jsonb.JSONField()),
                ('added', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'default_file_changes',
            },
        ),
        migrations.AddField(
            model_name='javaconfigchanges',
            name='config_key',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='javaconfigchanges',
            name='config_val',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='javaconfigchanges',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='javaconfigchanges',
            name='module',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ipadconfigchanges',
            name='table',
            field=models.TextField(blank=True, null=True),
        ),
    ]
