# Generated by Django 2.2.7 on 2020-12-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipad_config', '0006_auto_20201205_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticcontent',
            name='added_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
