# Generated by Django 3.2.13 on 2022-06-15 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiate', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='myimage')),
            ],
        ),
    ]
