# Generated by Django 3.2.13 on 2022-06-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiate', '0003_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.PositiveIntegerField()),
                ('is_deleted', models.PositiveIntegerField()),
                ('created_on', models.DateTimeField()),
                ('modified_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'floors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KeyCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.PositiveIntegerField()),
                ('is_deleted', models.PositiveIntegerField()),
                ('created_on', models.DateTimeField()),
                ('modified_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'key_categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('number_of_dvc', models.PositiveIntegerField()),
                ('number_of_ipad', models.PositiveIntegerField()),
                ('number_of_tv', models.PositiveIntegerField()),
                ('with_dvc', models.IntegerField()),
                ('is_handed_over', models.IntegerField()),
                ('communication_token', models.CharField(max_length=150)),
                ('wifi_token', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.PositiveIntegerField()),
                ('is_deleted', models.PositiveIntegerField()),
                ('created_on', models.DateTimeField()),
                ('modified_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'keys',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.PositiveIntegerField()),
                ('is_deleted', models.PositiveIntegerField()),
                ('created_on', models.DateTimeField()),
                ('modified_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=50)),
                ('contact_no', models.CharField(max_length=15)),
                ('ext_no', models.CharField(max_length=5)),
                ('role_id', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=128)),
                ('is_external', models.IntegerField()),
                ('is_active', models.PositiveIntegerField()),
                ('is_deleted', models.PositiveIntegerField()),
                ('created_by', models.PositiveIntegerField()),
                ('created_on', models.DateTimeField()),
                ('modified_by', models.PositiveIntegerField(blank=True, null=True)),
                ('modified_on', models.DateTimeField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
