# Generated by Django 3.2.13 on 2022-06-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiate', '0004_floors_keycategories_keys_users_wings'),
    ]

    operations = [
        migrations.CreateModel(
            name='logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
