# Generated by Django 3.2.13 on 2022-06-15 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initiate', '0006_delete_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='logo',
        ),
    ]
