dgjava_dict = {
    "DAS": "http://{DAS}",
    "DAS_SSL": "https://{DAS}",
    "DVS": "http://{DVS}",
    "DVS_SSL": "https://{DVS}",
    "HIS": "http://{HIS}",
    "HIS_SSL": "https://{HIS}",
    "MDS": "http://{MDS}",
    "MDS_SSL": "https://{MDS}",
    "VOD": "http://{VOD}",
    "VOD_SSL": "https://{VOD}",
    "BUTLER": "http://{BUTLER}",
    "BUTLER_SSL": "https://{BUTLER}",
    "DIGIVALET_API_HOST": "https://{HIS}/digivalet-api",
    "ONEAUTH_HOST": "https://{DAS}/oneauth",
    "DIGIMAILER_URL": "https://{DAS}/digimailer.php",
    "DVSERVICES_API_HOST": "https://{HIS}:8018",
    "BUTLER_DAS_SSL": "https://{DAS}/oneauth",
    "HOTEL_CODE": "OFFICE",
    "HOTEL_ID": 1,
    "SA_VENDOR": "DIGIVALET",
    "SA_VENDOR_URL": "",
    "SA_VENDOR_PASS": "",
    "SA_VENDOR_USER": "",
    "SA_VENDOR_PROPERTY_CODE": "",
    "SA_VENDOR_AUTH_URL": "",
    "SA_VENDOR_AUTH_ID": "",
    "SA_VENDOR_AUTH_SECRET": "",
    "REST_VENDOR": "DIGIVALET",
    "REST_VENDOR_URL": "",
    "REST_VENDOR_PASS": "",
    "REST_VENDOR_USER": "",

    "SPA_VENDOR": "DIGIVALET",
    "SPA_VENDOR_AUTH_ID": "",
    "SPA_VENDOR_AUTH_SECRET": "",
    "SPA_VENDOR_AUTH_URL": "",
    "SPA_VENDOR_PASS": "",
    "SPA_VENDOR_PROPERTY_CODE": "",
    "SPA_VENDOR_URL": "",
    "SPA_VENDOR_USER": "",
    "MSG_SERV_VENDOR": "",
    "PRINT_MAILER_SSL": "http://his.necker-island.digivalet.in:9004/printmail/performOrderAction",
    "BUTLER_PRINT_MAILER_SSL": "http://his.necker-island.digivalet.in:9004/printmail/mailOrderAction",
    "MESSAGE_SERV_SSL": "https://his.necker-island.digivalet.in:8018/communication-center/messages/send",

    "MESSAGE_URL": "",
    "MESSAGE_USER": "",
    "MESSAGE_PASS": "",
    "MESSAGE_FROM": "",
    "MESSAGE_TO": "",
    "DV_IRD_PRINTER": "dummy",
    "DV_REST_PRINTER": "dummy",
    "DV_SPA_PRINTER": "dummy",
    "DV_SA_PRINTER": "dummy",

    "POS_RETAIL_VENDOR": "DIGIVALET",
    "POS_RETAIL_VENDOR_AUTH_ID": "",
    "POS_RETAIL_VENDOR_AUTH_SECRET": "",
    "POS_RETAIL_VENDOR_AUTH_URL": "",
    "POS_RETAIL_VENDOR_PASS": "",
    "POS_RETAIL_VENDOR_PROPERTY_CODE": "",
    "POS_RETAIL_VENDOR_URL": "",
    "POS_RETAIL_VENDOR_USER": "",

    "POS_IRD_VENDOR": "DIGIVALET",
    "POS_IRD_APP_ID": "",
    "POS_IRD_URL": "",
    "POSI_RVC_ID": "RVC1001",

    "DVC_DATA_PORT": 9229,
    "BUTLER_CALL_SSL": "http://butler.necker-island.digivalet.in:9005/butler/callbutler",
    "ALERT_MAIL_ID": "",
    "PMS_SERVER": "127.0.0.1",
    "PMS_PORT": 7007,
    "PMS_VENDOR": "OPERA",
    "GATEWAY_SERV_SSL": "http://his.necker-island.digivalet.in:9008/gateway-services",

    "RMS_VENDOR": "",
    "GW_DVC_DATA_PORT": 9300,
    "PUSH_NOTIFY_URL": "",
    "INTERNET_SERV_VENDOR": "",
    "DVPOS_IRD_URL": "http://his.necker-island.digivalet.in:9001/posi/foodOrders/",

    "LOCK_VENDOR_URL": "",
    "LOCK_VENDOR": "",
    "LOCK_VENDOR_USER": "",
    "LOCK_VENDOR_PASS": "",
    "ZB_DVC_DATA_PORT": 9300,
    "MONITOR_LOG_TIME": 3000,

    "SMS_VENDOR": "",
    "SMS_TO": "",
    "SMS_FROM": "",
    "SMS_USER": "",
    "SMS_PASSWORD": "",
    "SMS_URL": "",

    "EPG_ACCESS_TOKEN": ""
}
